- mrrc/s3client.py
- setup.py
- tests/test_s3client.py
This change is adding an extra product parameter as the file metadata
to identify which products the file belongs to. With this change, the
upload of existed files will change to an metadata changing of adding
extra product but not the real file content override. And the delete
of files will also check if the products metadata is empty to decide
if the realy deletion will happen.
> Change the actions of upload_files and delete_files in s3client

- charon/constants.py
- template/index.html.j2
- tests/test_maven_index.py
- tests/test_npm_index.py
Found that CF can not look for index.html automatically as the root
page for a directory as httpd or nginx does, so we need to manually
add the trailing index.html for the dir link in index.html rendering.
> Fix: Add trailing index.html for indexing template rendering

- charon/storage.py
- tests/test_s3client.py
This function can just list the contents in specified folder without
full scan of s3 content, which is useful to do listing index
> Feat: Add list_folder_content function for s3 client

- charon/storage.py
For a single process (uploading|deleting), the bucket will not
change, so we should consider to cache the s3 bucket object for
performance.
> Feat: caching the aws bucket

- charon/pkgs/indexing.py
- charon/pkgs/maven.py
- charon/pkgs/npm.py
- tests/test_maven_index.py
- tests/test_npm_index.py
- tests/test_pkgs_dryrun.py
The old way of indexing generation function is using a .index file as
cache for each changed directory to avoid full scan of the whole s3
bucket, this brings bunch of complicated steps, like recursive folder
scan and reading, and local file reading of .index to do merging. The
new way is using a new function to scan and retrieving the contents
in a single folder, which is cheap way to get the contents to avoid
full scan.
> Refactor: change indexing generation function

- charon/cmd/command.py
- charon/config.py
- charon/pkgs/indexing.py
- charon/pkgs/maven.py
- charon/pkgs/npm.py
- charon/storage.py
- charon/utils/archive.py
- charon/utils/strings.py
- tests/base.py
- tests/test_maven_del.py
- tests/test_maven_index.py
- tests/test_maven_upload.py
- tests/test_s3client.py
This pr will let uploading and deletion process of maven releases have support to append the prefix as root dir to all files.
> Feat: Support prefix appending in maven uploading and deletion

- charon/cmd/command.py
- template/index.html.j2
This uses an unordered list instead of `pre` to avoid any residual problems with jinja template spacing, and sets the list style to avoid any item marker, and to place items outside the normal list indent.
> Fix: Make listing in index.html more compact

- charon/pkgs/indexing.py
- tests/test_indexing.py
Found that the index.html items list mixed between folders and files.
We need to let folders listed before files. This fix it.
> Fix: sort index.html items to make folder listed before

- charon/pkgs/maven.py
- charon/pkgs/pkg_utils.py
- charon/storage.py
- charon/utils/files.py
- tests/base.py
- tests/commons.py
- tests/test_maven_del.py
- tests/test_maven_index.py
- tests/test_maven_upload.py
- tests/test_npm_index.py
- tests/test_pkgs_dryrun.py
- tests/test_s3client.py
As maven-metadata.xml is generated by charon, we need also support
the digest files for this file, including md5, sha1 and sha256
> Fix: Add missing digest files for maven-metadata.xml

- charon/storage.py
This makes it a little easier to see how the upload is progressing, even though you really only have progress for each type of operation within the upload / delete.
> Add file progress counters to upload / delete logs

- charon/storage.py
- requirements.txt
- tests/commons.py
- tests/test_npm_del.py
- tests/test_npm_index.py
- tests/test_npm_upload.py
* Add type hint for s3 related objects
* Extract constants to tests.commons from npm tests
* Move some members and methods of S3Client to private
> Chore: some code optimization

- charon/constants.py
- charon/pkgs/npm.py
- charon/storage.py
- tests/base.py
- tests/commons.py
- tests/test_maven_del.py
- tests/test_maven_index.py
- tests/test_maven_upload.py
- tests/test_npm_del.py
- tests/test_npm_index.py
- tests/test_npm_upload.py
- tests/test_pkgs_dryrun.py
- tests/test_s3client.py
We found that AWS file metadata has length limitation, which means
not suitable to store long information like products info. So we need to
use a new file *.prodinfo for each uploaded files. Rules:
* Only product tarball valid files should contain this prodinfo file
* Metadta files like maven-metadata or npm package leveled
package.json or index files will not have this prodinfo.
> Feat: Use separate file to record product info

- charon/pkgs/maven.py
error-->warning as it is not a critical problem
> Chore: adjust log level for maven-metadata generation

- .github/workflows/linters.yaml
- .github/workflows/unittests.yaml
- test.sh
Caused by a yum repo "appstream". Seems centos8 always met yum repo  problem, so switched to centos7.
> Chore: fix github ci test failure

- charon/storage.py
* Make buckets cached in storage.py
> Preparation for multi-targets support

- charon/cmd/command.py
- charon/pkgs/indexing.py
- charon/pkgs/maven.py
- charon/pkgs/npm.py
- charon/pkgs/pkg_utils.py
- charon/storage.py
- tests/base.py
- tests/commons.py
- tests/test_manifest_del.py
- tests/test_manifest_upload.py
- tests/test_maven_del.py
- tests/test_maven_del_multi_tgts.py
- tests/test_maven_index.py
- tests/test_maven_index_multi_tgts.py
- tests/test_maven_upload.py
- tests/test_maven_upload_multi_tgts.py
- tests/test_npm_del.py
- tests/test_npm_del_multi_tgts.py
- tests/test_npm_index.py
- tests/test_npm_index_multi_tgts.py
- tests/test_npm_meta.py
- tests/test_npm_upload.py
- tests/test_npm_upload_multi_tgts.py
- tests/test_pkgs_dryrun.py
- tests/test_s3client.py
* Command options "target" can accept more than one targets now
* For files uploading, will pick first target as main target to do uploading, and then copy files from main target to other targets
* For files deletion, will delete from targets one by one
* All metadadata files updating will happened sequentially
* All s3 operations will happen asynchronously
> Feat: multi-targets support

- charon/pkgs/maven.py
- charon/pkgs/npm.py
- charon/storage.py
- tests/commons.py
Use bucket name instead of target name as it will not change.
> Fix: use bucket name as prefix for manifest file storage

- charon/pkgs/npm.py
- charon/storage.py
- tests/test_npm_dist_gen.py
Now considered npm version-level package.json is a sort of special metadata in Charon. It's partially generated from Charon, and most fields are coming from uploading. We still need to keep its .prodinfo to make it able to roll back thoroughly, so manifest will keep it as well.
> Convert npm version-level package.json as metadata partially

- .github/workflows/linters.yaml
- test.sh
* bandit failure because of underlying container, so disabled
* Fix pip install deprecation warning
> Chore: fix a github action issue

- charon/pkgs/npm.py
- charon/utils/map.py
- tests/test_npm_del.py
- tests/test_npm_del_multi_tgts.py
- tests/test_npm_meta.py
- tests/test_npm_upload.py
- tests/test_npm_upload_multi_tgts.py
> Fix a npm metadata serialization issue

- charon/pkgs/npm.py
- setup.py
- tests/test_npm_meta.py
- tests/test_npm_upload.py
- tests/test_npm_upload_multi_tgts.py
Recent fix has changed "dist_tags" to "dist-tags" usage, but forgot
to check the original content which has been published in Ronda,
which is still using "dist_tags". This makes the original content
miss the meta.dist_tags field, which caused error
> Fix missing check of the original malform "dist_tags"

- .gitignore
- README.md
- charon/cmd/__init__.py
- charon/cmd/cmd_index.py
- charon/pkgs/indexing.py
- charon/storage.py
- tests/test_maven_index.py
- tests/test_npm_index.py
- tests/test_s3client.py
To support refresh the index.html for a folder.
> Add command for re-index of folder

- charon.spec
- charon/storage.py
- requirements.txt
* Add new requires in spec file
* Remove duplicated requirements
* Little pydoc fix
> Some chore fix

- charon/cmd/__init__.py
- charon/cmd/cmd_cache.py
- charon/cmd/cmd_checksum.py
- charon/cmd/cmd_index.py
* Change checksum command name to checksum-validate
* Refine some help messages for the command
> Refine the command

- charon/cache.py
- charon/cmd/cmd_cache.py
- charon/cmd/cmd_delete.py
- charon/cmd/cmd_index.py
- charon/cmd/cmd_upload.py
- charon/cmd/internal.py
- charon/pkgs/pkg_utils.py
- charon/utils/logs.py
* Add switch to disable file log handler
* Use non-wildcard paths for invalidation
* Fix a targets check in command upload and delete
> Some updates

- charon/cache.py
- tests/test_cfclient.py
As aws can only process limit numbers of the paths in same time, whatever it is in single request or multiple, so we should control it by looping with sleep and check.
> Wait for each invalidation request's completion

- charon/cmd/__init__.py
- charon/cmd/cmd_cache.py
- charon/pkgs/pkg_utils.py
Extract cf-* commands to separate cf sub commands
> Add cf sub commands

- .pylintrc
- charon/utils/logs.py
And remove some invalid option for pylint checker
> Replace space in error log file name of product and version

- tests/requirements.txt
- tests/test_cf_reindex.py
- tests/test_cfclient.py
As moto 5.0.16 added support fot get_invalidation
> Enable test_check_invalidation for CloudFront test

- charon/pkgs/indexing.py
Seems the order of link items in the index.html for each folder is not correct. This PR will fix it.
> Fix mmeng-4362: re-sort the indexing page items

- charon/config.py
- charon/schemas/charon.json
- tests/test_config_radas.py
Add all needed radas configurations for mrrc signing.
> RADAS: add radas configurations

- charon/config.py
- charon/pkgs/radas_sign.py
- tests/test_radas_sign_receiver.py
- tests/test_radas_sign_sender.py
* Support timeout mechanism for Receiver exit
> Refactor: Refactor the RadasReceiver

- charon/config.py
- charon/pkgs/radas_sign.py
- tests/test_config_radas.py
As topic is also a valid destination to send, use queue is not
correct
> RADAS: change the request_queue to request_channel in config
