Commonjava/charon

maven_meta_test.py, mrrc/archive.py, mrrc/command.py, mrrc/config.py, mrrc/metadata_mvn.py, scan_maven.py, template/maven-metadata.xml.j2, zip_test.py
* And reformat indent to 4 spaces.
=> maven metadata generation base functions

config/mrrc-uploader.conf, mrrc/config.py, mrrc/utils/archive.py, tests/base.py, tests/test_config.py, tests/test_s3client.py
And some adjustment of fields in config.py
=> Adjustment for config: Add ignore_patterns config

mrrc/pkgs/maven.py, tests/test_maven_del.py, tests/test_maven_upload.py
To make test teardown to clear it easily
=> Add a base dir as hosted dir for tarball extraction

mrrc/storage.py, tests/test_s3client.py
=> Export some s3client functions

config/mrrc-uploader.conf, mrrc/cmd/command.py, mrrc/config.py, tests/test_config.py
Order is: sys env -> configuration -> default one
=> Support get aws bucket from system env var and configuration file

mrrc/cmd/command.py, mrrc/pkgs/maven.py, mrrc/storage.py, tests/test_maven_del.py, tests/test_maven_index.py, tests/test_maven_upload.py
* Remove ga flag in cmd as it is not used
* Adjust logging for index generation
=> Code adjustment

hermes/utils/archive.py
See https://semgrep.dev/orgs/commonjava/findings
=> Add a 30s timeout to archive download request

hermes/cmd/command.py, hermes/pkgs/maven.py, hermes/pkgs/npm.py, hermes/storage.py, tests/test_pkgs_dryrun.py
And also mark version option as required
=> Add dry-run support

charon/cmd/command.py, charon/pkgs/maven.py, charon/storage.py
* Product and version should not contain comma
* Some log info adjustment
=> chore: Add validation of param product and version

charon/constants.py, charon/pkgs/maven.py, charon/pkgs/npm.py, charon/storage.py, tests/test_npm_meta.py, tests/test_s3client.py
When calling boto3 s3 files listing with filter, it may get exception, we should take care of it
=> Fix: fix an error handling problem of s3 files get

charon/storage.py
AWS has transfer acceleration configuration to reduce uploading latency.
This commit will add a switch to choose if to enable this from client
side.
=> Feat: Add aws s3 acceleration enable support

charon/storage.py
Seems we missed the content-type for all files during uploading,
which will cause some problems of cloudfront file handling.
=> Fix: Add content-type for file in uploading

charon/cmd/command.py, charon/config.py, charon/pkgs/maven.py, charon/pkgs/npm.py, config/charon.conf, config/charon.yml, requirements.txt, tests/base.py, tests/test_config.py
New format of charon config file will be used:
* .ini format will be changed to yaml format
* Add targets to decide the target bucket and prefix
Some changes in command line
* Remove --bucket(-b) option from command line
* Add --target(-t) option
=> Change configuration file to charon.yaml

charon/cmd/command.py, charon/config.py, charon/pkgs/maven.py, charon/pkgs/npm.py, charon/storage.py
feat: add configuration option in charon.yaml for `aws_profile`
=> Feat: Support aws_profile configuration in charon.yaml

charon/pkgs/indexing.py, charon/pkgs/npm.py, tests/test_npm_del.py, tests/test_npm_index.py, tests/test_npm_upload.py
In ronda service we need to support to upload/delete files in specified prefix folders. This pr is addressing.
=> Feat: add prefix support to npm processing

charon/storage.py
Seems some s3 object metadata refreshing can also cause s3 exceptions, should avoid it cause command line crash.
=> Fix: add missing exception check for object metadata refreshing

charon/pkgs/maven.py
This change will surround the _parse_archetypes() call with a try/except clause, and attempt to take corrective action, as follows:
* If the parsing failure is in the local file, we will simply skip processing it and allow the remote content to remain as-is
* If the parsing failure is in the bucket file, we will either attempt to overwrite it (upload) or attempt to delete it (delete command)
=> Feat: Catch XML parsing error for archetype catalog

charon/constants.py, charon/pkgs/indexing.py, charon/pkgs/maven.py, charon/pkgs/npm.py, charon/utils/strings.py, test.sh, tests/commons.py, tests/test_npm_index.py, tests/test_pkgs_dryrun.py
We can change "package.json" in template easily if we decide to use another json file to present the content
=> fix npm index to display package.json on package folder

template/index.html.j2, tests/test_maven_del.py, tests/test_maven_upload.py
And remove duplications in some tests
=> Chore: a simple template change

requirements.txt
To avoid some api changes which could cause errors
=> Chore: Fixed the dep versions

charon/storage.py
We found that current performance bottleneck is the aws operations,
like uploading and files scanning. These operations are all heavy io
oriented, so to do improvement, we can use python asyncio to refactor
the code.
This commit will use asyncio to make all AWS heavy io operations run
in async mode. And to control the resource usage, will limit the
concurrent coroutines to 100.
=> Feat: enable async uploading with asyncio

charon/pkgs/maven.py, charon/pkgs/npm.py, charon/storage.py
And also added a new logger to record the progress of files operated every 1000 count.
=> Chore: down level logging of individual files operations for s3

setup.py
* MMENG-3153
Signed-off-by: Harsh Modi <hmodi@redhat.com>
=> bump charon version

README.md, charon/cmd/command.py, charon/pkgs/maven.py, charon/pkgs/npm.py, charon/pkgs/signature.py
As request of REs, add rpm-sign alone-side with gpg
=> add rpm-sign as method of signature

charon/cache.py, charon/pkgs/indexing.py, charon/pkgs/maven.py, charon/pkgs/npm.py, charon/pkgs/pkg_utils.py, tests/test_cf_reindex.py, tests/test_cfclient.py, tests/test_maven_index.py, tests/test_npm_index.py
* And ignore the indexing(index.html) CF invalidating per cost consideration
* And change the root work dir for npm uploading
=> Use wildcard for paths in maven CF invalidating

charon/cache.py, charon/pkgs/indexing.py
* HTML indexing: remove first redundant slash for list items
* Add some bucket to domain mapping for CF
=> Fix two issues

charon/cmd/__init__.py, charon/cmd/cmd_cache.py, charon/cmd/cmd_checksum.py, charon/pkgs/checksum_http.py, charon/storage.py, charon/utils/files.py, tests/test_checksum_refresh.py, tests/test_s3client.py
This command will refresh the checksums for a maven artifact in Ronda
maven repository.
=> Add new refresh checksum cmd

.gitignore, requirements.txt
Just need semantic-version instead of setuptools-rust
=> Adjust requirements.txt
